// test
POST http://localhost:3000/users
content-type: application/json

{
  "name": "test",
  "email": "nicosohta0318@gamil.com",
  "password": "Sohta0318"
}

# create income
POST http://localhost:3000/users
content-type: application/json

{
  "name": "test",
  "email": "nicosohta0318@gamil.com",
  "password": "Sohta0318"
}